
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "E:/ciloion/CLion 2025.3.4/bin/cmake/win/x64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
